.TH MYAPP 1
.SH NAME
Myapp \- A simple demonstration application that does very little.
.SH SYNOPSIS
.B myapp
[\-option ...]
.SH DESCRIPTION
.PP
\fImyapp\fP is a complete application that does nothing useful.
.PP
It was written for demonstration purpose.
.SH OPTIONS
.PP
It doesn't have any, but let's pretend, to make this template complete;
.SH COPYRIGHT
myapp is Copyright (c) 2018 Diwen.Liu
.SH BUGS
There probably some, but I don't know what they are yet.
.SH AUTHORS
Diwen.Liu
