start:
	gcc -g -Wall getname.c -o getname
	gcc -g -Wall getdate_tcp.c -o getdate_tcp
	gcc -g -Wall select.c -o select
	gcc -g -Wall getdate_udp.c -o getdate_udp

clean:
	@rm -f getname getdate_tcp select getdate_udp
