#! /bin/bash

# 把PATH环境变量中的路径逐行打印出来

path=:${PATH} # 在前面加一个:，便于连续参数扩展至空字符

while [ "$path" != "" ]; do
	sub_path=${path##*:}	# 截取到的路径（最后一个）
	path=${path%:*}		# 把已经截取的路径删除，继续截取
	echo $sub_path
done

exit 0
