# Makefile 例子

# Which compiler
CC = gcc

# Where to install
INSTDIR = ./bin

# Where are include files kept
INCLUDE = .

# Options for development
CFlags = -g -Wall

# Options for release
# CFLAGS = -O -Wall

LIBCORE = libcore.a

$(LIBCORE): $(LIBCORE)(core.o)

clean:
	-rm -f libcore.a
